import Image from "next/image";
import Link from "next/link";
import {homeCopy, type SupportedLocale} from "@/content/locale-copy";

export default function Home({locale = "en"}: {locale?: SupportedLocale}) {
  const t = homeCopy[locale];
  return <main id="main">
    <section className="hero" id="home"><div className="hero-copy reveal"><p className="eyebrow">{t.eyebrow}</p><h1>{t.heroTitle}</h1><p className="intro">{t.heroText}</p><div className="actions"><a className="button primary" href="#contact">{t.prayerAction}</a><a className="text-link" href="#groups">{t.groupsAction}</a></div></div><div className="hero-art"><Image src="/assets/hero-community.png" alt="Familias de la comunidad acercándose a una iglesia" width={1672} height={941} priority /></div></section>
    <section className="live-panel" id="live"><div><p className="live-status"><i />{t.liveStatus}</p><h2>{t.liveTitle}</h2><p>{t.liveText}</p></div><a className="button light" href="#live">{t.watchLive}</a></section>
    <section className="section services" id="groups"><div className="section-heading"><p className="eyebrow">{t.communityLabel}</p><h2>{t.communityTitle}</h2></div><div className="service-grid"><article><span className="service-icon">♙</span><h3>Small groups</h3><p>Small groups, also known as cells, are a fundamental part of our service to God.</p><a href="#contact">Join a group</a></article><article><span className="service-icon">✦</span><h3>Training</h3><p>In Jesus we see grace and truth in fullness. We grow by looking to Him.</p><a href="#contact">Learn more</a></article><article><span className="service-icon">♡</span><h3>Plenitude groups</h3><p>Marriage, youth, health, and family — every part of life is explored in light of Scripture.</p><a href="#contact">Discover groups</a></article></div></section>
    <section className="section about" id="about"><div className="about-image"><Image src="/assets/small-group.png" alt="Grupo pequeño estudiando la Biblia y conversando" width={1536} height={1024} /></div><div><p className="eyebrow">{t.aboutLabel}</p><h2>{t.aboutTitle}</h2><p>{t.aboutText}</p><Link className="text-link" href={locale === "en" ? "/pastors/" : `/${locale}/pastors/`}>{t.meetPastors}</Link></div></section>
    <section className="section contact" id="contact"><div><p className="eyebrow">{t.contactLabel}</p><h2>{t.contactTitle}</h2><p className="address">5000 Spencer St<br />Las Vegas, NV 89119</p><a className="button secondary" href="https://www.google.com/maps/dir/?api=1&destination=5000+Spencer+St,+Las+Vegas,+NV+89119" target="_blank" rel="noreferrer">{t.directions}</a></div><div className="map-wrap" style={{minHeight:350,overflow:"hidden",border:"1px solid #397195",borderRadius:18}}><iframe title="Iglesia Plenitud en Cristo - 5000 Spencer St, Las Vegas" style={{display:"block",width:"100%",height:350,border:0}} src="https://www.google.com/maps?q=5000%20Spencer%20St%2C%20Las%20Vegas%2C%20NV%2089119&z=15&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><form className="prayer-form"><h3>{t.prayerTitle}</h3><label><span>{t.name}</span><input name="name" autoComplete="name" disabled /></label><label><span>{t.email}</span><input type="email" name="email" autoComplete="email" disabled /></label><label><span>{t.request}</span><textarea name="request" rows={4} disabled /></label><button className="button primary" type="button" disabled>{t.send}</button><p className="form-message" role="status">Prayer requests are temporarily unavailable. We are preparing this service and will have it available soon.</p></form></section>
    <section className="culture section"><p className="eyebrow">{t.visionLabel}</p><h2>{t.visionTitle}</h2><p className="vision-copy">Reaching homes to proclaim Jesus Christ, reconciling nonbelievers with God, and forming them as disciples who live and serve in the Holy Spirit.</p><div className="culture-grid"><article><strong className="culture-icon">⌂</strong><h3>Reach</h3><p>We bring Christ’s love to every home.</p></article><article><strong className="culture-icon">♙</strong><h3>Strengthen</h3><p>We accompany and strengthen people in faith and unity.</p></article><article><strong className="culture-icon">✦</strong><h3>Form</h3><p>Disciples with mature service and strong character.</p></article><article><strong className="culture-icon">◎</strong><h3>Send</h3><p>We inspire people to impact the world with Christ’s love.</p></article></div><div className="pillars"><span>Presence</span><span>Character</span><span>Service</span></div><blockquote>“We live in God’s presence, walk in obedience, celebrate with joy and faith, love and care with integrity, welcome with hospitality, and serve with humility.”</blockquote><p className="schedule">Sundays 6 PM · Wednesdays 7 PM · 702 328 2536</p></section>
    <section className="social-panel"><div><p className="eyebrow">Stay connected</p><h2>Follow our community on Instagram.</h2><p>See news, moments of faith, and upcoming activities from our community.</p></div><a className="button secondary" href="https://www.instagram.com/prmarioalsina">Open Instagram</a></section>
  </main>;
}
