import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return <main id="main">
    <section className="hero" id="home"><div className="hero-copy reveal"><p className="eyebrow">A place to grow, belong, and serve</p><h1>Grow in your spiritual life.</h1><p className="intro">We are here to walk with you, listen with care, and pray sincerely for your life.</p><div className="actions"><a className="button primary" href="#contact">Request prayer</a><a className="text-link" href="#groups">Explore our groups <span>→</span></a></div></div><div className="hero-art"><Image src="/assets/hero-community.png" alt="Familias de la comunidad acercándose a una iglesia" width={1672} height={941} priority /></div></section>
    <section className="live-panel" id="live"><div><p className="live-status"><i />Live now</p><h2>Join us in today’s service</h2><p>The live service will appear here whenever the church is broadcasting.</p></div><a className="button light" href="#live">Watch live</a></section>
    <section className="section services" id="groups"><div className="section-heading"><p className="eyebrow">Our community</p><h2>There is a place for you here.</h2></div><div className="service-grid"><article><span className="service-icon">♙</span><h3>Small groups</h3><p>Small groups, also known as cells, are a fundamental part of our service to God.</p><a href="#contact">Join a group</a></article><article><span className="service-icon">✦</span><h3>Training</h3><p>In Jesus we see grace and truth in fullness. We grow by looking to Him.</p><a href="#contact">Learn more</a></article><article><span className="service-icon">♡</span><h3>Plenitude groups</h3><p>Marriage, youth, health, and family — every part of life is explored in light of Scripture.</p><a href="#contact">Discover groups</a></article></div></section>
    <section className="section about" id="about"><div className="about-image"><Image src="/assets/small-group.png" alt="Grupo pequeño estudiando la Biblia y conversando" width={1536} height={1024} /></div><div><p className="eyebrow">Get to know us</p><h2>Rooted in Christ. Open to you.</h2><p>We seek to be a healthy, biblical, spiritual, and multiplying church: reaching lives, reconciling people with God, forming disciples, and sending them to serve.</p><Link className="text-link" href="/pastors/">Meet our pastors <span>→</span></Link></div></section>
    <section className="section contact" id="contact"><div><p className="eyebrow">We would love to meet you</p><h2>Come as you are.</h2><p className="address">5000 Spencer St<br />Las Vegas, NV 89119</p><a className="button secondary" href="https://www.google.com/maps/dir/?api=1&destination=5000+Spencer+St,+Las+Vegas,+NV+89119" target="_blank" rel="noreferrer">Get directions</a></div><div className="map-wrap" style={{minHeight:350,overflow:"hidden",border:"1px solid #397195",borderRadius:18}}><iframe title="Iglesia Plenitud en Cristo - 5000 Spencer St, Las Vegas" style={{display:"block",width:"100%",height:350,border:0}} src="https://www.google.com/maps?q=5000%20Spencer%20St%2C%20Las%20Vegas%2C%20NV%2089119&z=15&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><form className="prayer-form"><h3>How can we pray for you?</h3><label><span>Name</span><input name="name" autoComplete="name" disabled /></label><label><span>Email</span><input type="email" name="email" autoComplete="email" disabled /></label><label><span>Prayer request</span><textarea name="request" rows={4} disabled /></label><button className="button primary" type="button" disabled>Send request</button><p className="form-message" role="status">Prayer requests are temporarily unavailable. We are preparing this service and will have it available soon.</p></form></section>
    <section className="culture section"><p className="eyebrow">Our vision</p><h2>Reach, strengthen, form, and send.</h2><p className="vision-copy">Reaching homes to proclaim Jesus Christ, reconciling nonbelievers with God, and forming them as disciples who live and serve in the Holy Spirit.</p><div className="culture-grid"><article><strong className="culture-icon">⌂</strong><h3>Reach</h3><p>We bring Christ’s love to every home.</p></article><article><strong className="culture-icon">♙</strong><h3>Strengthen</h3><p>We accompany and strengthen people in faith and unity.</p></article><article><strong className="culture-icon">✦</strong><h3>Form</h3><p>Disciples with mature service and strong character.</p></article><article><strong className="culture-icon">◎</strong><h3>Send</h3><p>We inspire people to impact the world with Christ’s love.</p></article></div><div className="pillars"><span>Presence</span><span>Character</span><span>Service</span></div><blockquote>“We live in God’s presence, walk in obedience, celebrate with joy and faith, love and care with integrity, welcome with hospitality, and serve with humility.”</blockquote><p className="schedule">Sundays 6 PM · Wednesdays 7 PM · 702 328 2536</p></section>
    <section className="social-panel"><div><p className="eyebrow">Stay connected</p><h2>Follow our community on Instagram.</h2><p>See news, moments of faith, and upcoming activities from our community.</p></div><a className="button secondary" href="https://www.instagram.com/prmarioalsina">Open Instagram</a></section>
  </main>;
}
