import Image from "next/image";
import type {Metadata} from "next";
import {pastorsCopy} from "@/content/pastors-copy";
import type {SupportedLocale} from "@/content/locale-copy";

const baseUrl = "https://demo.suplenitud.com";
export const metadata: Metadata = {title: "Pastors | Iglesia Plenitud en Cristo", description: "Meet the pastoral team of Iglesia Plenitud en Cristo.", alternates: {canonical: `${baseUrl}/pastors/`, languages: {en: `${baseUrl}/pastors/`, es: `${baseUrl}/es/pastors/`, pt: `${baseUrl}/pt/pastors/`, ko: `${baseUrl}/ko/pastors/`, de: `${baseUrl}/de/pastors/`}}, openGraph: {url: `${baseUrl}/pastors/`, locale: "en"}};

export default function PastorsPage({locale = "en"}: {locale?: SupportedLocale}) {
  const t = pastorsCopy[locale];
  return <main className="pastors-page" lang={locale}><section className="pastors-hero"><div><p className="eyebrow">{t.heroEyebrow}</p><h1>{t.heroTitle}</h1><p>{t.heroText}</p></div></section><section className="pastor-story section"><div className="pastor-photo"><Image src="/assets/small-group.png" alt="Comunidad estudiando la Biblia" width={1536} height={1024} /></div><div><p className="eyebrow">{t.marioEyebrow}</p><h2>{t.marioTitle}</h2><p>{t.marioText1}</p><p>{t.marioText2}</p><a className="text-link" href="https://www.globalharvestonline.com/quienes-somos" target="_blank" rel="noreferrer">{t.ghtiLink}</a></div></section><section className="section journey"><p className="eyebrow">{t.journeyEyebrow}</p><h2>{t.journeyTitle}</h2><div className="journey-grid"><article><span>01</span><h3>{t.step1Title}</h3><p>{t.step1Text}</p></article><article><span>02</span><h3>{t.step2Title}</h3><p>{t.step2Text}</p></article><article><span>03</span><h3>{t.step3Title}</h3><p>{t.step3Text}</p></article><article><span>04</span><h3>{t.step4Title}</h3><p>{t.step4Text}</p></article></div></section><section className="section adriana"><div><p className="eyebrow">{t.adrianaEyebrow}</p><h2>{t.adrianaTitle}</h2><p>{t.adrianaText1}</p><p>{t.adrianaText2}</p></div><div className="values"><p>{t.valuesLabel}</p><ul><li>{t.value1}</li><li>{t.value2}</li><li>{t.value3}</li><li>{t.value4}</li></ul></div></section><section className="instagram section"><p className="eyebrow">{t.instagramEyebrow}</p><h2>{t.instagramTitle}</h2><p>{t.instagramText}</p><a className="button secondary" href="https://www.instagram.com/prmarioalsina" target="_blank" rel="noreferrer">{t.instagramAction}</a></section></main>;
}
