export const supportedLocales = ["en", "es", "pt", "ko", "de"] as const;
export type SupportedLocale = (typeof supportedLocales)[number];

type HomeCopy = {
  eyebrow: string; heroTitle: string; heroText: string; prayerAction: string; groupsAction: string;
  liveStatus: string; liveTitle: string; liveText: string; watchLive: string; communityLabel: string; communityTitle: string;
  aboutLabel: string; aboutTitle: string; aboutText: string; meetPastors: string; contactLabel: string; contactTitle: string;
  directions: string; prayerTitle: string; name: string; email: string; request: string; send: string; unavailableNotice: string; visionLabel: string; visionTitle: string;
};

export const homeCopy: Record<SupportedLocale, HomeCopy> = {
  en: {eyebrow:"A place to grow, belong, and serve",heroTitle:"Grow in your spiritual life.",heroText:"We are here to walk with you, listen with care, and pray sincerely for your life.",prayerAction:"Request prayer",groupsAction:"Explore our groups →",liveStatus:"Live now",liveTitle:"Join us in today’s service",liveText:"The live service will appear here whenever the church is broadcasting.",watchLive:"Watch live",communityLabel:"Our community",communityTitle:"There is a place for you here.",aboutLabel:"Get to know us",aboutTitle:"Rooted in Christ. Open to you.",aboutText:"We seek to be a healthy, biblical, spiritual, and multiplying church: reaching lives, reconciling people with God, forming disciples, and sending them to serve.",meetPastors:"Meet our pastors →",contactLabel:"We would love to meet you",contactTitle:"Come as you are.",directions:"Get directions",prayerTitle:"How can we pray for you?",name:"Name",email:"Email",request:"Prayer request",send:"Send",unavailableNotice:"Prayer requests are temporarily unavailable. We are preparing this service and will have it available soon.",visionLabel:"Our vision",visionTitle:"Reach, strengthen, form, and send."},
  es: {eyebrow:"Un lugar para crecer, pertenecer y servir",heroTitle:"Crece en tu vida espiritual.",heroText:"Estamos aquí para caminar contigo, escucharte con atención y orar con sinceridad por tu vida.",prayerAction:"Pide oración",groupsAction:"Conoce nuestros grupos →",liveStatus:"En vivo ahora",liveTitle:"Acompáñanos en el servicio de hoy",liveText:"La transmisión aparecerá aquí cuando la iglesia esté en vivo.",watchLive:"Ver en vivo",communityLabel:"Nuestra comunidad",communityTitle:"Hay un lugar para ti aquí.",aboutLabel:"Conócenos",aboutTitle:"Firmes en Cristo. Abiertos para ti.",aboutText:"Queremos ser una iglesia saludable, bíblica, espiritual y multiplicadora: alcanzando vidas, reconciliando con Dios, formando discípulos y enviándolos a servir.",meetPastors:"Conoce a nuestros pastores →",contactLabel:"Nos encantaría conocerte",contactTitle:"Ven tal como eres.",directions:"Cómo llegar",prayerTitle:"¿Cómo podemos orar por ti?",name:"Nombre",email:"Correo electrónico",request:"Petición de oración",send:"Enviar",unavailableNotice:"Las peticiones de oración están temporalmente no disponibles. Estamos preparando este servicio y pronto estará disponible.",visionLabel:"Nuestra visión",visionTitle:"Alcanzar, consolidar, formar y enviar."},
  pt: {eyebrow:"Um lugar para crescer, pertencer e servir",heroTitle:"Cresça em sua vida espiritual.",heroText:"Estamos aqui para caminhar com você, ouvir com atenção e orar sinceramente por sua vida.",prayerAction:"Pedir oração",groupsAction:"Conheça nossos grupos →",liveStatus:"Ao vivo agora",liveTitle:"Junte-se a nós no culto de hoje",liveText:"A transmissão aparecerá aqui quando a igreja estiver ao vivo.",watchLive:"Assistir ao vivo",communityLabel:"Nossa comunidade",communityTitle:"Há um lugar para você aqui.",aboutLabel:"Conheça-nos",aboutTitle:"Firmes em Cristo. Abertos para você.",aboutText:"Buscamos ser uma igreja saudável, bíblica, espiritual e multiplicadora: alcançando vidas, reconciliando pessoas com Deus, formando discípulos e enviando-os para servir.",meetPastors:"Conheça nossos pastores →",contactLabel:"Adoraríamos conhecê-lo",contactTitle:"Venha como você é.",directions:"Como chegar",prayerTitle:"Como podemos orar por você?",name:"Nome",email:"E-mail",request:"Pedido de oração",send:"Enviar",unavailableNotice:"Os pedidos de oração estão temporariamente indisponíveis. Estamos preparando este serviço e ele estará disponível em breve.",visionLabel:"Nossa visão",visionTitle:"Alcançar, consolidar, formar e enviar."},
  ko: {eyebrow:"성장하고, 속하고, 섬기는 곳",heroTitle:"영적 삶 안에서 성장하세요.",heroText:"우리는 당신과 함께 걷고, 주의 깊게 듣고, 당신의 삶을 위해 진심으로 기도합니다.",prayerAction:"기도 요청",groupsAction:"소그룹 알아보기 →",liveStatus:"지금 생방송",liveTitle:"오늘 예배에 함께하세요",liveText:"교회가 방송 중일 때 이곳에 생방송이 표시됩니다.",watchLive:"라이브 시청",communityLabel:"우리 공동체",communityTitle:"당신을 위한 자리가 있습니다.",aboutLabel:"교회 소개",aboutTitle:"그리스도 안에 굳게. 당신에게 열려 있습니다.",aboutText:"우리는 건강하고 성경적이며 영적이고 성장하는 교회가 되어, 생명을 살리고, 하나님과 화해시키며, 제자를 세우고 섬기도록 보냅니다.",meetPastors:"목회자 소개 →",contactLabel:"만나 뵙기를 바랍니다",contactTitle:"있는 모습 그대로 오세요.",directions:"길찾기",prayerTitle:"어떻게 기도해 드릴까요?",name:"이름",email:"이메일",request:"기도 제목",send:"보내기",unavailableNotice:"기도 요청은 현재 이용할 수 없습니다. 이 서비스를 준비하고 있으며 곧 제공할 예정입니다.",visionLabel:"우리의 비전",visionTitle:"전하고, 세우고, 훈련하고, 보냅니다."},
  de: {eyebrow:"Ein Ort zum Wachsen, Dazugehören und Dienen",heroTitle:"Wachse in deinem geistlichen Leben.",heroText:"Wir sind hier, um mit dir zu gehen, aufmerksam zuzuhören und aufrichtig für dein Leben zu beten.",prayerAction:"Gebet erbitten",groupsAction:"Unsere Gruppen entdecken →",liveStatus:"Jetzt live",liveTitle:"Sei beim heutigen Gottesdienst dabei",liveText:"Die Liveübertragung erscheint hier, sobald die Gemeinde sendet.",watchLive:"Live ansehen",communityLabel:"Unsere Gemeinschaft",communityTitle:"Hier ist ein Platz für dich.",aboutLabel:"Lerne uns kennen",aboutTitle:"Fest in Christus. Offen für dich.",aboutText:"Wir wollen eine gesunde, biblische, geistliche und wachsende Gemeinde sein: Leben erreichen, Menschen mit Gott versöhnen, Jünger formen und sie zum Dienen senden.",meetPastors:"Unsere Pastoren kennenlernen →",contactLabel:"Wir möchten dich kennenlernen",contactTitle:"Komm, wie du bist.",directions:"Wegbeschreibung",prayerTitle:"Wie können wir für dich beten?",name:"Name",email:"E-Mail",request:"Gebetsanliegen",send:"Senden",unavailableNotice:"Gebetsanliegen sind vorübergehend nicht verfügbar. Wir bereiten diesen Dienst vor und werden ihn bald anbieten.",visionLabel:"Unsere Vision",visionTitle:"Erreichen, stärken, formen und senden."}
};

type HomeExtraCopy = {smallTitle:string;smallText:string;join:string;trainingTitle:string;trainingText:string;learn:string;plenitudeTitle:string;plenitudeText:string;discover:string;visionText:string;reach:string;reachText:string;strengthen:string;strengthenText:string;form:string;formText:string;sendText:string;presence:string;character:string;service:string;cultureQuote:string;schedule:string;socialLabel:string;socialTitle:string;socialText:string;socialAction:string};

export const homeExtraCopy: Record<SupportedLocale, HomeExtraCopy> = {
  en:{smallTitle:"Small groups",smallText:"Small groups, also known as cells, are a fundamental part of our service to God.",join:"Join a group",trainingTitle:"Training",trainingText:"In Jesus we see grace and truth in fullness. We grow by looking to Him.",learn:"Learn more",plenitudeTitle:"Plenitude groups",plenitudeText:"Marriage, youth, health, and family — every part of life is explored in light of Scripture.",discover:"Discover groups",visionText:"Reaching homes to proclaim Jesus Christ, reconciling nonbelievers with God, and forming them as disciples who live and serve in the Holy Spirit.",reach:"Reach",reachText:"We bring Christ’s love to every home.",strengthen:"Strengthen",strengthenText:"We accompany and strengthen people in faith and unity.",form:"Form",formText:"Disciples with mature service and strong character.",sendText:"We inspire people to impact the world with Christ’s love.",presence:"Presence",character:"Character",service:"Service",cultureQuote:"“We live in God’s presence, walk in obedience, celebrate with joy and faith, love and care with integrity, welcome with hospitality, and serve with humility.”",schedule:"Sundays 6 PM · Wednesdays 7 PM · 702 328 2536",socialLabel:"Stay connected",socialTitle:"Follow our community on Instagram.",socialText:"See news, moments of faith, and upcoming activities from our community.",socialAction:"Open Instagram"},
  es:{smallTitle:"Grupos pequeños",smallText:"Los grupos pequeños, también conocidos como células, son parte fundamental de nuestro servicio a Dios.",join:"Únete a un grupo",trainingTitle:"Entrenamiento",trainingText:"En Jesús vemos gracia y verdad en plenitud. Crecemos al mirarlo a Él.",learn:"Conoce más",plenitudeTitle:"Grupos de plenitud",plenitudeText:"Matrimonio, juventud, salud y familia: cada área de la vida se estudia a la luz de las Escrituras.",discover:"Descubre grupos",visionText:"Alcanzar a los hogares para anunciar a Jesucristo, reconciliar a los no creyentes con Dios y formarlos como discípulos que viven y sirven en el Espíritu Santo.",reach:"Alcanzar",reachText:"Llevamos el amor de Cristo a cada hogar.",strengthen:"Consolidar",strengthenText:"Acompañamos y fortalecemos en la fe y la unidad.",form:"Formar",formText:"Discípulos con un servicio maduro y un gran carácter.",sendText:"Impulsamos a impactar al mundo con el amor de Cristo.",presence:"Presencia",character:"Carácter",service:"Servicio",cultureQuote:"“Vivimos en la presencia de Dios, caminamos en obediencia, celebramos con gozo y fe, amamos y cuidamos con integridad, recibimos con hospitalidad y servimos con humildad.”",schedule:"Domingos 6 PM · Miércoles 7 PM · 702 328 2536",socialLabel:"Mantente conectado",socialTitle:"Sigue a nuestra comunidad en Instagram.",socialText:"Mira noticias, momentos de fe y próximas actividades de nuestra comunidad.",socialAction:"Abrir Instagram"},
  pt:{smallTitle:"Pequenos grupos",smallText:"Os pequenos grupos, também conhecidos como células, são parte fundamental do nosso serviço a Deus.",join:"Entre em um grupo",trainingTitle:"Treinamento",trainingText:"Em Jesus vemos graça e verdade em plenitude. Crescemos olhando para Ele.",learn:"Saiba mais",plenitudeTitle:"Grupos de plenitude",plenitudeText:"Casamento, juventude, saúde e família: cada área da vida é estudada à luz das Escrituras.",discover:"Descubra grupos",visionText:"Alcançar os lares para anunciar Jesus Cristo, reconciliar os não crentes com Deus e formá-los como discípulos que vivem e servem no Espírito Santo.",reach:"Alcançar",reachText:"Levamos o amor de Cristo a cada lar.",strengthen:"Consolidar",strengthenText:"Acompanhamos e fortalecemos na fé e na unidade.",form:"Formar",formText:"Discípulos com serviço maduro e grande caráter.",sendText:"Inspiramos a impactar o mundo com o amor de Cristo.",presence:"Presença",character:"Caráter",service:"Serviço",cultureQuote:"“Vivemos na presença de Deus, caminhamos em obediência, celebramos com alegria e fé, amamos e cuidamos com integridade, acolhemos com hospitalidade e servimos com humildade.”",schedule:"Domingos 18h · Quartas-feiras 19h · 702 328 2536",socialLabel:"Mantenha-se conectado",socialTitle:"Siga nossa comunidade no Instagram.",socialText:"Veja notícias, momentos de fé e próximas atividades da nossa comunidade.",socialAction:"Abrir Instagram"},
  ko:{smallTitle:"소그룹",smallText:"셀이라고도 하는 소그룹은 하나님을 섬기는 데 중요한 부분입니다.",join:"그룹 참여하기",trainingTitle:"훈련",trainingText:"예수님 안에서 우리는 충만한 은혜와 진리를 봅니다. 우리는 그분을 바라보며 성장합니다.",learn:"더 알아보기",plenitudeTitle:"플레니투드 그룹",plenitudeText:"결혼, 청소년, 건강, 가족 등 삶의 모든 영역을 성경의 빛 아래서 나눕니다.",discover:"그룹 알아보기",visionText:"가정에 예수 그리스도를 전하고, 믿지 않는 이들을 하나님과 화해시키며, 성령 안에서 살고 섬기는 제자로 세웁니다.",reach:"전하기",reachText:"모든 가정에 그리스도의 사랑을 전합니다.",strengthen:"세우기",strengthenText:"믿음과 연합 안에서 함께하며 강하게 합니다.",form:"훈련하기",formText:"성숙한 섬김과 굳건한 인격을 가진 제자.",sendText:"그리스도의 사랑으로 세상에 영향을 주도록 보냅니다.",presence:"임재",character:"인격",service:"섬김",cultureQuote:"“우리는 하나님의 임재 안에 살고, 순종으로 걷고, 기쁨과 믿음으로 축하하며, 정직하게 사랑하고 돌보고, 환대로 맞이하며 겸손히 섬깁니다.”",schedule:"주일 오후 6시 · 수요일 오후 7시 · 702 328 2536",socialLabel:"연결 유지",socialTitle:"Instagram에서 우리 공동체를 팔로우하세요.",socialText:"우리 공동체의 소식, 믿음의 순간, 앞으로의 활동을 확인하세요.",socialAction:"Instagram 열기"},
  de:{smallTitle:"Kleingruppen",smallText:"Kleingruppen, auch Zellen genannt, sind ein grundlegender Teil unseres Dienstes für Gott.",join:"Einer Gruppe beitreten",trainingTitle:"Schulung",trainingText:"In Jesus sehen wir Gnade und Wahrheit in ihrer Fülle. Wir wachsen, indem wir auf ihn schauen.",learn:"Mehr erfahren",plenitudeTitle:"Plenitud-Gruppen",plenitudeText:"Ehe, Jugend, Gesundheit und Familie: Jeder Lebensbereich wird im Licht der Heiligen Schrift betrachtet.",discover:"Gruppen entdecken",visionText:"Wir erreichen Familien, um Jesus Christus zu verkünden, versöhnen Nichtgläubige mit Gott und formen sie zu Jüngern, die im Heiligen Geist leben und dienen.",reach:"Erreichen",reachText:"Wir bringen Christi Liebe in jedes Zuhause.",strengthen:"Stärken",strengthenText:"Wir begleiten und stärken im Glauben und in der Einheit.",form:"Formen",formText:"Jünger mit reifem Dienst und starkem Charakter.",sendText:"Wir ermutigen Menschen, die Welt mit Christi Liebe zu prägen.",presence:"Gegenwart",character:"Charakter",service:"Dienst",cultureQuote:"“Wir leben in Gottes Gegenwart, gehen im Gehorsam, feiern mit Freude und Glauben, lieben und sorgen mit Integrität, heißen mit Gastfreundschaft willkommen und dienen in Demut.”",schedule:"Sonntags 18 Uhr · Mittwochs 19 Uhr · 702 328 2536",socialLabel:"In Verbindung bleiben",socialTitle:"Folge unserer Gemeinschaft auf Instagram.",socialText:"Sieh Neuigkeiten, Glaubensmomente und bevorstehende Aktivitäten unserer Gemeinschaft.",socialAction:"Instagram öffnen"}
};
