export const supportedLocales = ["en", "es", "pt", "ko", "de"] as const;
export type SupportedLocale = (typeof supportedLocales)[number];

type HomeCopy = {
  eyebrow: string; heroTitle: string; heroText: string; prayerAction: string; groupsAction: string;
  liveStatus: string; liveTitle: string; liveText: string; watchLive: string; communityLabel: string; communityTitle: string;
  aboutLabel: string; aboutTitle: string; aboutText: string; meetPastors: string; contactLabel: string; contactTitle: string;
  directions: string; prayerTitle: string; name: string; email: string; request: string; send: string; visionLabel: string; visionTitle: string;
};

export const homeCopy: Record<SupportedLocale, HomeCopy> = {
  en: {eyebrow:"A place to grow, belong, and serve",heroTitle:"Grow in your spiritual life.",heroText:"We are here to walk with you, listen with care, and pray sincerely for your life.",prayerAction:"Request prayer",groupsAction:"Explore our groups →",liveStatus:"Live now",liveTitle:"Join us in today’s service",liveText:"The live service will appear here whenever the church is broadcasting.",watchLive:"Watch live",communityLabel:"Our community",communityTitle:"There is a place for you here.",aboutLabel:"Get to know us",aboutTitle:"Rooted in Christ. Open to you.",aboutText:"We seek to be a healthy, biblical, spiritual, and multiplying church: reaching lives, reconciling people with God, forming disciples, and sending them to serve.",meetPastors:"Meet our pastors →",contactLabel:"We would love to meet you",contactTitle:"Come as you are.",directions:"Get directions",prayerTitle:"How can we pray for you?",name:"Name",email:"Email",request:"Prayer request",send:"Send",visionLabel:"Our vision",visionTitle:"Reach, strengthen, form, and send."},
  es: {eyebrow:"Un lugar para crecer, pertenecer y servir",heroTitle:"Crece en tu vida espiritual.",heroText:"Estamos aquí para caminar contigo, escucharte con atención y orar con sinceridad por tu vida.",prayerAction:"Pide oración",groupsAction:"Conoce nuestros grupos →",liveStatus:"En vivo ahora",liveTitle:"Acompáñanos en el servicio de hoy",liveText:"La transmisión aparecerá aquí cuando la iglesia esté en vivo.",watchLive:"Ver en vivo",communityLabel:"Nuestra comunidad",communityTitle:"Hay un lugar para ti aquí.",aboutLabel:"Conócenos",aboutTitle:"Firmes en Cristo. Abiertos para ti.",aboutText:"Queremos ser una iglesia saludable, bíblica, espiritual y multiplicadora: alcanzando vidas, reconciliando con Dios, formando discípulos y enviándolos a servir.",meetPastors:"Conoce a nuestros pastores →",contactLabel:"Nos encantaría conocerte",contactTitle:"Ven tal como eres.",directions:"Cómo llegar",prayerTitle:"¿Cómo podemos orar por ti?",name:"Nombre",email:"Correo electrónico",request:"Petición de oración",send:"Enviar",visionLabel:"Nuestra visión",visionTitle:"Alcanzar, consolidar, formar y enviar."},
  pt: {eyebrow:"Um lugar para crescer, pertencer e servir",heroTitle:"Cresça em sua vida espiritual.",heroText:"Estamos aqui para caminhar com você, ouvir com atenção e orar sinceramente por sua vida.",prayerAction:"Pedir oração",groupsAction:"Conheça nossos grupos →",liveStatus:"Ao vivo agora",liveTitle:"Junte-se a nós no culto de hoje",liveText:"A transmissão aparecerá aqui quando a igreja estiver ao vivo.",watchLive:"Assistir ao vivo",communityLabel:"Nossa comunidade",communityTitle:"Há um lugar para você aqui.",aboutLabel:"Conheça-nos",aboutTitle:"Firmes em Cristo. Abertos para você.",aboutText:"Buscamos ser uma igreja saudável, bíblica, espiritual e multiplicadora: alcançando vidas, reconciliando pessoas com Deus, formando discípulos e enviando-os para servir.",meetPastors:"Conheça nossos pastores →",contactLabel:"Adoraríamos conhecê-lo",contactTitle:"Venha como você é.",directions:"Como chegar",prayerTitle:"Como podemos orar por você?",name:"Nome",email:"E-mail",request:"Pedido de oração",send:"Enviar",visionLabel:"Nossa visão",visionTitle:"Alcançar, consolidar, formar e enviar."},
  ko: {eyebrow:"성장하고, 속하고, 섬기는 곳",heroTitle:"영적 삶 안에서 성장하세요.",heroText:"우리는 당신과 함께 걷고, 주의 깊게 듣고, 당신의 삶을 위해 진심으로 기도합니다.",prayerAction:"기도 요청",groupsAction:"소그룹 알아보기 →",liveStatus:"지금 생방송",liveTitle:"오늘 예배에 함께하세요",liveText:"교회가 방송 중일 때 이곳에 생방송이 표시됩니다.",watchLive:"라이브 시청",communityLabel:"우리 공동체",communityTitle:"당신을 위한 자리가 있습니다.",aboutLabel:"교회 소개",aboutTitle:"그리스도 안에 굳게. 당신에게 열려 있습니다.",aboutText:"우리는 건강하고 성경적이며 영적이고 성장하는 교회가 되어, 생명을 살리고, 하나님과 화해시키며, 제자를 세우고 섬기도록 보냅니다.",meetPastors:"목회자 소개 →",contactLabel:"만나 뵙기를 바랍니다",contactTitle:"있는 모습 그대로 오세요.",directions:"길찾기",prayerTitle:"어떻게 기도해 드릴까요?",name:"이름",email:"이메일",request:"기도 제목",send:"보내기",visionLabel:"우리의 비전",visionTitle:"전하고, 세우고, 훈련하고, 보냅니다."},
  de: {eyebrow:"Ein Ort zum Wachsen, Dazugehören und Dienen",heroTitle:"Wachse in deinem geistlichen Leben.",heroText:"Wir sind hier, um mit dir zu gehen, aufmerksam zuzuhören und aufrichtig für dein Leben zu beten.",prayerAction:"Gebet erbitten",groupsAction:"Unsere Gruppen entdecken →",liveStatus:"Jetzt live",liveTitle:"Sei beim heutigen Gottesdienst dabei",liveText:"Die Liveübertragung erscheint hier, sobald die Gemeinde sendet.",watchLive:"Live ansehen",communityLabel:"Unsere Gemeinschaft",communityTitle:"Hier ist ein Platz für dich.",aboutLabel:"Lerne uns kennen",aboutTitle:"Fest in Christus. Offen für dich.",aboutText:"Wir wollen eine gesunde, biblische, geistliche und wachsende Gemeinde sein: Leben erreichen, Menschen mit Gott versöhnen, Jünger formen und sie zum Dienen senden.",meetPastors:"Unsere Pastoren kennenlernen →",contactLabel:"Wir möchten dich kennenlernen",contactTitle:"Komm, wie du bist.",directions:"Wegbeschreibung",prayerTitle:"Wie können wir für dich beten?",name:"Name",email:"E-Mail",request:"Gebetsanliegen",send:"Senden",visionLabel:"Unsere Vision",visionTitle:"Erreichen, stärken, formen und senden."}
};
